// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrrqqfqtxoorwemkdtgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycnFxZnF0eG9vcndlbWtkdGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwOTQxMzksImV4cCI6MjA2MjY3MDEzOX0.5icHdH2g2iayTrm9R2ignilO9OeYJj41bCMsjJMXnco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);